### ISSUE TITLE
Accidently deleting entries that are not visible.

### ISSUE THREAD

**Issue by SodiumShine** [jltaylor-us/StardewToDew#1]
If you have a list that is long enough that it can be scrolled or navigated using arrows, clicking outside of the interface deletes items that would be there would the list be longer.

This is a little difficult to explain so I'll use a picture. Basically, if you have a long list, clicking the circled spaces sometimes deletes entries that you can't see. That includes clicking on the input field.

![image](https://user-images.githubusercontent.com/4461697/104990540-f351e680-5a70-11eb-88a4-4d5d8cb0c618.png)

**Comment by jltaylor-us** [comment]
Fixed in 1.4.1.  Thanks for the report!
