### ISSUE TITLE
Wouldn't It Be Better If The List Would Scale With Ui Level Rather Than Zoom Level ?

### ISSUE THREAD

**Issue by Nitbundier** [jltaylor-us/StardewToDew#6]
Wouldn't It Be Better If The List Would Scale With Ui Level Rather Than Zoom Level ?
edit: Changing Scale in configs would be a Good option

**Comment by jltaylor-us** [comment]
Version 1.11.0 adds on option to toggle whether the overlay is scaled with UI Scale or Zoom Level

**Comment by Azzurite** [comment]
@jltaylor-us love it! Thank you so much!
